version: '3.1'

networks:
  shelter-net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.40.200/29

volumes:
  pg_data:

services:

  shelter-postgresql:
    container_name: shelter-postgresql
    image: shelter-postgresql
    build:
      context: ./docker-images/postgresql/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    networks:
      shelter-net:
        ipv4_address: 172.20.40.202
    ports:
      - ${POSTGRES_PORTS}
    volumes:
      - pg_data:/shelter/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  shelter-web:
    container_name: shelter-web
    image: shelter-web
    build:
      context: ./docker-images/web/
    depends_on:
      - shelter-postgresql
    restart: always
    networks:
      shelter-net:
        ipv4_address: 172.20.40.203
    ports:
      - ${WEB_PORTS}


